---
- name: Download and install AlertLogic Agent
  hosts: localhost
  become: true
  gather_facts: false
  ignore_unreachable: true
  ignore_errors: true

  vars:
    agent_rpm_url: https://scc.alertlogic.net/software/al-agent-LATEST-1.x86_64.rpm
    agent_rpm_dest: /tmp/al-agent-LATEST-1.x86_64.rpm
    min_version: "2.20"

  tasks:
    - name: Ensure the dnf Python module is installed
      dnf:
        name: python3-dnf
        state: present

    - name: Check if AlertLogic Agent is installed
      shell: rpm -qa | grep al-agent
      register: al_agent_installed
      changed_when: false
      ignore_errors: true

    - name: Check if AlertLogic Agent is running
      shell: /etc/init.d/al-agent status
      register: al_agent_running
      changed_when: false
      ignore_errors: true
      when: al_agent_installed.rc == 0

    - name: Get AlertLogic Agent version
      shell: rpm -qi al-agent | grep Version | awk '{print $3}'
      register: al_agent_version
      changed_when: false
      ignore_errors: true
      when: al_agent_installed.rc == 0

    - name: Set flag if agent is installed, running, and version is above 2.20
      set_fact:
        agent_ok: "{{ (al_agent_installed.rc == 0) and (al_agent_running.rc == 0) and (al_agent_version.stdout is version(min_version, '>=')) }}"

    - name: End play if agent is installed, running, and above version 2.20
      meta: end_host
      when: agent_ok

    - name: Install required packages
      dnf:
        name: rsyslog
        state: present

    - name: Download AlertLogic agent RPM
      get_url:
        url: "{{ agent_rpm_url }}"
        dest: "{{ agent_rpm_dest }}"

    - name: Remove existing AlertLogic Agent and directory
      shell: |
        dnf remove -y al-agent
        rm -rf /var/alertlogic

    - name: Install the AlertLogic Agent
      dnf:
        name: "{{ agent_rpm_dest }}"
        state: present

    - name: Check SELinux status
      command: getenforce
      register: selinux

    - name: Set SELinux port if enforcing
      command: semanage port -a -t syslogd_port_t -p tcp 1514
      when: selinux.stdout == "Enforcing"

    - name: Start AlertLogic agent
      command: /etc/init.d/al-agent start

    - name: Check if rsyslog daemon is active
      command: systemctl is-active rsyslog
      register: rsyslog_status
      changed_when: false
      ignore_errors: true

    - name: Check if syslog-ng daemon is active
      command: systemctl is-active syslog-ng
      register: syslog_ng_status
      changed_when: false
      ignore_errors: true

    - name: Set fact for rsyslog daemon
      set_fact:
        syslog_daemon: "rsyslog"
      when: rsyslog_status.stdout == "active" and syslog_ng_status.rc != 0

    - name: Set fact for syslog-ng daemon
      set_fact:
        syslog_daemon: "syslog-ng"
      when: syslog_ng_status.stdout == "active" and rsyslog_status.rc != 0

    - name: Set fallback fact
      set_fact:
        syslog_daemon: "rsyslog"
      when: rsyslog_status.stdout != "active" and syslog_ng_status.stdout != "active"

    - name: Configure rsyslog
      block:
        - name: Add setting in rsyslog.conf
          lineinfile:
            path: /etc/rsyslog.conf
            line: "*.* @@127.0.0.1:1514;RSYSLOG_FileFormat"
            state: present

        - name: Restart rsyslog service
          systemd:
            name: rsyslog
            state: restarted
      when: syslog_daemon == "rsyslog"

    - name: Configure syslog-ng
      block:
        - name: Add setting 1 in syslog-ng.conf 
          lineinfile:
            path: /etc/syslog-ng/syslog-ng.conf
            line: 'destination d_alertlogic {tcp("localhost" port(1514));};'
            insertafter: '^destination*'

        - name: Add setting 2 in syslog-ng.conf 
          lineinfile:
            path: /etc/syslog-ng/syslog-ng.conf
            line: 'log { source(s_sys); destination(d_alertlogic); };'
            insertafter: '^log*'

        - name: Restart syslog-ng service
          systemd:
            name: syslog-ng
            state: restarted
      when: syslog_daemon == "syslog-ng"

    - name: Delete al-agent rpm file from tmp
      file:
        path: "{{ agent_rpm_dest }}"
        state: absent

    - name: Check if AlertLogic Agent is installed
      shell: rpm -qa | grep al-agent
      register: al_agent_installed
      changed_when: false

    - name: Check if AlertLogic Agent is running
      shell: /etc/init.d/al-agent status
      register: al_agent_running
      changed_when: false

    - name: Display Existing Status
      debug:
        msg: |
          AlertLogic Agent is {% if al_agent_installed.rc == 0 %} Installed {% else %} NOT Installed {% endif %} and {% if al_agent_running.rc == 0 %} Running {% else %} NOT Running {% endif %}
